# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kraigochieng@gmail.com
author_name: kraigochieng
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: demo-contracts

